### ISSUE TITLE
Est of CQL support

### ISSUE THREAD

**Issue by vuleetu** [carloscm/gossie#13]
What is the estimation of supporting CQL? thanks.

**Comment by carloscm** [comment]
There is no estimate for supporting CQL in Gossie. Starting from CQL 3.0 Cassandra is moving away from the Thrift RPC protocol towards a new, native custom protocol. Since Gossie is wrapper for the Thrift RPC interface there is not much sense into implementing support for this new protocol (it would require new connection/pool/networking code, all new data types and abstractions, etc).

If you want to use CQL with Go I recommend this module:

https://github.com/tux21b/gocql
